import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fal: IconPack;

export const faAddressBook: IconDefinition;
export const faBlockBrickFire: IconDefinition;
export const faCalendarDay: IconDefinition;
export const faChartLine: IconDefinition;
export const faClipboardList: IconDefinition;
export const faClockRotateLeft: IconDefinition;
export const faCloud: IconDefinition;
export const faCubes: IconDefinition;
export const faEnvelope: IconDefinition;
export const faGear: IconDefinition;
export const faGlobe: IconDefinition;
export const faGrid2: IconDefinition;
export const faHeadset: IconDefinition;
export const faHouse: IconDefinition;
export const faList: IconDefinition;
export const faMessage: IconDefinition;
export const faNetworkWired: IconDefinition;
export const faServer: IconDefinition;
export const faShieldHalved: IconDefinition;
export const faStar: IconDefinition;
export const faUserGroup: IconDefinition;
export const faUsers: IconDefinition;
