import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fas: IconPack;

export const faAiSpark: IconDefinition;
export const faArrowsRepeat: IconDefinition;
export const faBlockBrickFire: IconDefinition;
export const faBrokenRepeat: IconDefinition;
export const faBuildings: IconDefinition;
export const faCameraSecurity: IconDefinition;
export const faChildTask: IconDefinition;
export const faCircleCompleting: IconDefinition;
export const faClose: IconDefinition;
export const faDisplaySlash: IconDefinition;
export const faDoubleExclamation: IconDefinition;
export const faEarListen: IconDefinition;
export const faElaborate: IconDefinition;
export const faEmptySet: IconDefinition;
export const faGrid2: IconDefinition;
export const faGridDividers: IconDefinition;
export const faGridOne: IconDefinition;
export const faGridRound: IconDefinition;
export const faHangup: IconDefinition;
export const faMissed: IconDefinition;
export const faOfficePhone: IconDefinition;
export const faOpen: IconDefinition;
export const faParentTask: IconDefinition;
export const faPhoneArrowDownLeft: IconDefinition;
export const faRecord: IconDefinition;
export const faShorten: IconDefinition;
export const faSum: IconDefinition;
export const faTrafficCone: IconDefinition;
